"""
publish_to_tableau_cloud.py

Publishes Finished_Merged.hyper to Tableau Cloud as a published data source
and applies the metadata generated by generate_metadata.py
(datasource_metadata.json): name, description, tags, certification, and
per-column field descriptions.

Column descriptions are applied by editing the datasource's own .tds XML
directly and republishing it -- not via Tableau Catalog / the Metadata API.
See apply_column_descriptions() below for why: Catalog's column-description
REST endpoint only works for datasources traceable to a live external
database connection, which a directly-uploaded .hyper file doesn't have.
This was confirmed by testing against a live site before switching approach.

Configuration is read from environment variables -- see .env.example for
the full list and what each one means. Copy .env.example to .env, fill in
your real values, and this script loads it automatically via python-dotenv.

Never commit .env, paste its contents into chat, or share it: it holds a
Tableau Personal Access Token that can publish/overwrite content on your site.

Usage:
    python3 publish_to_tableau_cloud.py
"""

import io
import json
import os
import xml.etree.ElementTree as ET
import zipfile

import tableauserverclient as TSC
from dotenv import load_dotenv

TABLEAU_USER_NS = "http://www.tableausoftware.com/xml/user"
ET.register_namespace("user", TABLEAU_USER_NS)

LOCAL_TYPE_TO_TABLEAU = {
    "string": ("string", "dimension", "nominal"),
    "integer": ("integer", "measure", "quantitative"),
    "real": ("real", "measure", "quantitative"),
    "date": ("date", "dimension", "ordinal"),
    "datetime": ("datetime", "dimension", "ordinal"),
    "boolean": ("boolean", "dimension", "nominal"),
}

HYPER_FILE = "Finished_Merged.hyper"
METADATA_FILE = "datasource_metadata.json"

REQUIRED_ENV_VARS = [
    "TABLEAU_SERVER_URL",
    "TABLEAU_SITE_CONTENT_URL",
    "TABLEAU_PROJECT_NAME",
    "TABLEAU_TOKEN_NAME",
    "TABLEAU_TOKEN_SECRET",
]


def load_config():
    load_dotenv()
    missing = [v for v in REQUIRED_ENV_VARS if not os.environ.get(v)]
    if missing:
        raise SystemExit(
            "Missing required environment variable(s): "
            + ", ".join(missing)
            + "\nCopy .env.example to .env and fill in your Tableau Cloud details."
        )
    return {
        "server_url": os.environ["TABLEAU_SERVER_URL"],
        "site_content_url": os.environ["TABLEAU_SITE_CONTENT_URL"],
        "project_name": os.environ["TABLEAU_PROJECT_NAME"],
        "token_name": os.environ["TABLEAU_TOKEN_NAME"],
        "token_secret": os.environ["TABLEAU_TOKEN_SECRET"],
        "datasource_name": os.environ.get("TABLEAU_DATASOURCE_NAME", "Finished Merged"),
    }


def load_metadata():
    if not os.path.exists(METADATA_FILE):
        raise SystemExit(f"{METADATA_FILE} not found. Run generate_metadata.py first.")
    with open(METADATA_FILE) as f:
        return json.load(f)


def find_project(server, project_name):
    for project in TSC.Pager(server.projects):
        if project.name == project_name:
            return project
    raise SystemExit(
        f"Project {project_name!r} not found on this site. "
        f"Check TABLEAU_PROJECT_NAME in .env -- the project must already exist."
    )


def _set_column_desc(column_element, text):
    for child in list(column_element):
        if child.tag == "desc":
            column_element.remove(child)
    desc = ET.SubElement(column_element, "desc")
    formatted_text = ET.SubElement(desc, "formatted-text")
    run = ET.SubElement(formatted_text, "run")
    run.text = text


def _patch_tds_column_descriptions(tds_bytes, columns_metadata):
    """
    Adds/updates a <desc> on the .tds's top-level <column> element for each
    field named in columns_metadata, creating the <column> element itself
    when the field doesn't have one yet (true for any field that was never
    renamed/edited in Tableau -- it only exists as a <metadata-record>, which
    is not something Tableau's Fields tab reads a description from).

    Returns (new_xml_bytes, updated_count, created_count).
    """
    root = ET.fromstring(tds_bytes)

    local_type_by_field = {}
    for metadata_record in root.iter("metadata-record"):
        if metadata_record.get("class") != "column":
            continue
        local_name_el = metadata_record.find("local-name")
        local_type_el = metadata_record.find("local-type")
        if local_name_el is None or local_type_el is None:
            continue
        local_type_by_field[local_name_el.text] = local_type_el.text

    existing_columns = {c.get("name"): c for c in root.findall("column")}

    connection_el = root.find("connection")
    insert_index = list(root).index(connection_el) + 1 if connection_el is not None else 0

    updated, created = 0, 0
    for col in columns_metadata:
        name = f"[{col['name']}]"
        text = (col.get("description") or "").strip()
        if not text or text == "No description available.":
            continue

        if name in existing_columns:
            _set_column_desc(existing_columns[name], text)
            updated += 1
        else:
            local_type = local_type_by_field.get(name, "string")
            datatype, role, type_ = LOCAL_TYPE_TO_TABLEAU.get(local_type, ("string", "dimension", "nominal"))
            new_col = ET.Element("column", {"datatype": datatype, "name": name, "role": role, "type": type_})
            _set_column_desc(new_col, text)
            root.insert(insert_index, new_col)
            insert_index += 1
            created += 1

    return ET.tostring(root, encoding="utf-8", xml_declaration=True), updated, created


def apply_column_descriptions(server, datasource_item, columns_metadata):
    """
    Sets per-column field descriptions by downloading the just-published
    datasource as a .tdsx, patching <column>/<desc> elements directly into
    its embedded .tds XML, and republishing with Overwrite.

    This does NOT use Tableau Catalog or the Metadata API. That path was
    tried first and confirmed, against a live site, not to work here:
    Catalog's column-description REST endpoint (PUT .../tables/{id}/columns/{id})
    only manages tables traceable to a live external database connection.
    A directly-uploaded .hyper file has none, so Catalog never registers a
    manageable Table for it -- verified by checking the exact table/column
    IDs the Metadata API reported against every catalog table on the site
    (zero match), including the field-level upstreamColumnsConnection path
    that avoids the separate Metadata-node-ID-vs-REST-LUID pitfall. Editing
    the datasource's own .tds is connection-independent: it's the
    datasource's definition file, not a derived Catalog record, so it works
    the same way regardless of whether the source is an extract or a live
    connection. Verified end-to-end against a live site: republished, then
    re-downloaded and confirmed the descriptions were actually there.

    A failure here never aborts the publish -- name/description/tags/
    certification have already been applied by this point.
    """
    if not columns_metadata:
        return

    tdsx_path = None
    try:
        # download() appends its own extension to whatever path is passed in,
        # so the actual saved path must be read from its return value.
        tdsx_path = server.datasources.download(
            datasource_item.id, filepath=f"{datasource_item.name}.download", include_extract=True
        )
        with open(tdsx_path, "rb") as f:
            original_tdsx = f.read()
    except Exception as e:
        print(f"Skipping column descriptions -- could not download the published datasource: {e}")
        return
    finally:
        if tdsx_path and os.path.exists(tdsx_path):
            os.remove(tdsx_path)

    with zipfile.ZipFile(io.BytesIO(original_tdsx)) as zf:
        tds_names = [n for n in zf.namelist() if n.endswith(".tds")]
        if not tds_names:
            print("Skipping column descriptions -- no .tds file found inside the downloaded .tdsx.")
            return
        tds_path = tds_names[0]
        tds_bytes = zf.read(tds_path)

    new_tds_bytes, updated, created = _patch_tds_column_descriptions(tds_bytes, columns_metadata)
    if updated == 0 and created == 0:
        print("Skipping republish -- no column descriptions matched any field.")
        return

    out = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(original_tdsx)) as zin, zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zout:
        for info in zin.infolist():
            payload = zin.read(info.filename)
            if info.filename == tds_path:
                payload = new_tds_bytes
            zout.writestr(info, payload)
    out.seek(0)

    try:
        server.datasources.publish(datasource_item, out, TSC.Server.PublishMode.Overwrite)
    except Exception as e:
        print(f"Could not republish with column descriptions: {e}")
        return

    print(f"Republished with column descriptions: {updated} updated, {created} newly created.")


def main():
    config = load_config()
    metadata = load_metadata()
    ds_meta = metadata["datasource"]

    if not os.path.exists(HYPER_FILE):
        raise SystemExit(f"{HYPER_FILE} not found. Run split_by_year.py then union_hyper_files.py first.")

    tableau_auth = TSC.PersonalAccessTokenAuth(
        config["token_name"], config["token_secret"], site_id=config["site_content_url"]
    )
    server = TSC.Server(config["server_url"], use_server_version=True)

    with server.auth.sign_in(tableau_auth):
        project = find_project(server, config["project_name"])

        # Name, description, and certification must be set on the DatasourceItem
        # BEFORE publish(): the update-after-publish request does not include
        # description at all (verified against tableauserverclient's request
        # builder), so setting it after the fact would silently do nothing.
        new_datasource = TSC.DatasourceItem(project_id=project.id, name=config["datasource_name"])
        new_datasource.description = ds_meta.get("description")
        new_datasource.certified = bool(ds_meta.get("certified", False))
        if ds_meta.get("certification_note"):
            new_datasource.certification_note = ds_meta["certification_note"]

        print(
            f"Publishing {HYPER_FILE} to project {config['project_name']!r} "
            f"as {config['datasource_name']!r}..."
        )
        published_ds = server.datasources.publish(
            new_datasource, HYPER_FILE, TSC.Server.PublishMode.Overwrite
        )
        print(f"Published. Data source ID: {published_ds.id}")
        print(f"URL: {config['server_url']}/#/site/{config['site_content_url']}/datasources/{published_ds.id}")

        # Tags are NOT part of the publish payload either -- they require a
        # separate call against the /tags endpoint.
        tags = set(ds_meta.get("tags", []))
        if tags:
            published_ds.tags = tags
            server.datasources.update_tags(published_ds)
            print(f"Applied tags: {sorted(tags)}")

        apply_column_descriptions(server, published_ds, metadata.get("columns", []))

    print("Done.")


if __name__ == "__main__":
    main()
