"""
generate_metadata.py

Inspects a .hyper file (given via --source) and writes a metadata JSON
file describing it: name, description, tags, certification status, and
per-column descriptions -- all derived from the file's own schema and data,
not from any hand-written, dataset-specific knowledge. This is a generic
tool: point it at any single-table .hyper extract and it profiles whatever
columns are actually there.

Column descriptions are generated by profiling each column's own values --
its type, how many distinct values it has, and either a min/max range
(numeric, date, or time columns) or a handful of sample values (low-
cardinality text/boolean columns). This describes the *shape* of the data,
not what it *means* -- this script has no domain knowledge of the dataset,
so review and edit the generated descriptions before treating them as
documentation. See COLUMN_DESCRIPTION_DISCLAIMER below, which is also
carried into the output JSON so it isn't lost downstream.

publish_to_tableau_cloud.py reads this file's output (via its own
--metadata flag) and applies the datasource-level fields (name,
description, tags, certification) and per-column descriptions to the
published data source.

Calculated fields cannot be profiled from data -- their formulas are
author-supplied. If the output file already contains a "calculations"
block, this script carries it forward unchanged when re-profiling, so
regenerating the metadata never wipes hand-added calculated fields.
publish_to_tableau_cloud.py applies that block too.

Usage (run from the project root; paths are just examples -- this is a generic
tool that accepts any single-table .hyper file):
    python3 scripts/generate_metadata.py --source=<file>.hyper [options]

    --source is required -- there is no default .hyper file.

    python3 scripts/generate_metadata.py --source=data/Finished_Merged.hyper --output=data/datasource_metadata.json
        Profiles data/Finished_Merged.hyper and writes the metadata JSON to
        data/datasource_metadata.json (the filename committed in this repo).
        If --output is omitted it defaults to the --source path with its
        extension swapped from .hyper to .json (e.g. data/Finished_Merged.json),
        so it's always obvious which metadata file goes with which .hyper file.
        The datasource name is derived from the filename (underscores -> spaces)
        unless --name overrides it; tags, certification, and certification note
        default to none/false/empty unless --tags/--certified/--certification-note
        are given.

    python3 scripts/generate_metadata.py --source=data/Some_Other_Extract.hyper --output=data/some_other_metadata.json \\
        --name "Some Other Extract" --tags team-a,quarterly --certified --certification-note "Reviewed by BI team"
        Profiles a different file, writes to an explicitly chosen output
        path instead of the derived default, and sets every datasource-level
        field explicitly instead of relying on the derived/empty defaults.
"""

import argparse
import json
import os
from datetime import datetime, timezone

from tableauhyperapi import (
    Connection,
    HyperException,
    HyperProcess,
    Nullability,
    SchemaName,
    TableName,
    Telemetry,
    TypeTag,
)

SOURCE_USAGE = "--source=<path-to-file>.hyper"
SCHEMA_NAME = "public"
TABLE = "Extract"

# Types profiled with a MIN/MAX range (numeric, date, and time-like columns).
RANGE_TAGS = {
    TypeTag.SMALL_INT, TypeTag.INT, TypeTag.BIG_INT,
    TypeTag.DOUBLE, TypeTag.FLOAT, TypeTag.NUMERIC, TypeTag.OID,
    TypeTag.DATE, TypeTag.TIMESTAMP, TypeTag.TIMESTAMP_TZ, TypeTag.TIME,
}
# Types profiled by distinct-value count, with sample values shown when
# there are few enough of them to actually be categorical.
CATEGORICAL_TAGS = {TypeTag.TEXT, TypeTag.CHAR, TypeTag.VARCHAR, TypeTag.BOOL}
# Tags used to pick the "primary" date column for the datasource-level
# description/stats (the first column with one of these types, if any).
DATE_TAGS = {TypeTag.DATE, TypeTag.TIMESTAMP, TypeTag.TIMESTAMP_TZ}

NO_DESCRIPTION = "No description available."
CATEGORICAL_SAMPLE_LIMIT = 10  # show sample values only at or below this many distinct values
CATEGORICAL_SAMPLE_SIZE = 6    # how many sample values to quote when showing them

COLUMN_DESCRIPTION_DISCLAIMER = (
    "Column descriptions were generated automatically by profiling each "
    "column's own data (type, distinct-value count, and either a value "
    "range or a few sample values) -- they describe the shape of the data, "
    "not what it means. This script has no domain knowledge of the "
    "dataset. Review and edit before treating them as documentation."
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Inspect a .hyper file and write a metadata JSON file describing it, for publish_to_tableau_cloud.py's --metadata flag."
    )
    parser.add_argument(
        "--source",
        metavar="FILE.hyper",
        help="Path to the .hyper file to inspect, e.g. --source=Finished_Merged.hyper. Required -- there is no default.",
    )
    parser.add_argument(
        "--output",
        metavar="FILE.json",
        help=(
            "Path to write the metadata JSON to. Defaults to the --source "
            "path with its extension swapped from .hyper to .json, e.g. "
            "Finished_Merged.hyper -> Finished_Merged.json."
        ),
    )
    parser.add_argument(
        "--name",
        metavar="NAME",
        help="Datasource name to record. Defaults to the --source filename (underscores -> spaces).",
    )
    parser.add_argument(
        "--tags",
        metavar="TAG,TAG,...",
        default="",
        help="Comma-separated tags to record for the datasource. Defaults to none.",
    )
    parser.add_argument(
        "--certified",
        action="store_true",
        help="Mark the datasource as certified in the generated metadata. Defaults to false.",
    )
    parser.add_argument(
        "--certification-note",
        metavar="TEXT",
        default="",
        help="Certification note to record (only meaningful together with --certified).",
    )
    return parser.parse_args()


def get_table_definition(connection, hyper_file):
    table_name = TableName(SCHEMA_NAME, TABLE)
    try:
        return table_name, connection.catalog.get_table_definition(table_name)
    except HyperException:
        available = [
            str(t) for t in connection.catalog.get_table_names(SchemaName(SCHEMA_NAME))
        ]
        raise SystemExit(
            f"Table {table_name} not found in {hyper_file!r}. "
            f"Table(s) actually present in schema {SCHEMA_NAME!r}: {available or '(none)'}. "
            "This script only profiles Tableau's conventional single-table "
            "extract layout (schema 'public', table 'Extract')."
        )


def describe_column(connection, table_name, col, row_count):
    """
    Builds a description for a column purely from its own data -- this
    script has no idea what the column *means*, only what's in it.
    """
    tag = col.type.tag
    quoted = f'"{col.name.unescaped}"'

    if row_count == 0:
        return f"{col.type} column. Table is empty -- no values to profile."

    if tag not in RANGE_TAGS and tag not in CATEGORICAL_TAGS:
        return NO_DESCRIPTION

    if tag in RANGE_TAGS:
        try:
            distinct_count, min_val, max_val = connection.execute_list_query(
                f"SELECT COUNT(DISTINCT {quoted}), MIN({quoted}), MAX({quoted}) FROM {table_name}"
            )[0]
        except HyperException:
            return NO_DESCRIPTION
        return (
            f"{col.type} column with {distinct_count} distinct value(s), "
            f"ranging from {min_val} to {max_val}."
        )

    # tag in CATEGORICAL_TAGS
    try:
        distinct_count = connection.execute_scalar_query(
            f"SELECT COUNT(DISTINCT {quoted}) FROM {table_name}"
        )
    except HyperException:
        return NO_DESCRIPTION

    if distinct_count <= CATEGORICAL_SAMPLE_LIMIT:
        samples = [
            row[0]
            for row in connection.execute_list_query(
                f"SELECT DISTINCT {quoted} FROM {table_name} "
                f"ORDER BY {quoted} LIMIT {CATEGORICAL_SAMPLE_SIZE}"
            )
        ]
        sample_text = ", ".join(repr(s) for s in samples)
        return f"{col.type} column with {distinct_count} distinct value(s), e.g. {sample_text}."

    return f"{col.type} column with {distinct_count} distinct value(s) out of {row_count} row(s)."


def find_date_stats(connection, table_name, table_def):
    """
    Picks the first DATE/TIMESTAMP(_TZ)-typed column, if any, and reports
    its min/max range and the distinct years it spans -- used for the
    datasource-level description, not per-column descriptions. Returns
    None if the table has no such column, rather than assuming one exists.
    """
    date_col = next((c for c in table_def.columns if c.type.tag in DATE_TAGS), None)
    if date_col is None:
        return None

    quoted = f'"{date_col.name.unescaped}"'
    date_min, date_max = connection.execute_list_query(
        f"SELECT MIN({quoted}), MAX({quoted}) FROM {table_name}"
    )[0]
    years = [
        row[0]
        for row in connection.execute_list_query(
            f"SELECT DISTINCT EXTRACT(YEAR FROM {quoted}) AS yr FROM {table_name} ORDER BY yr"
        )
    ]
    return {
        "column": date_col.name.unescaped,
        "min": str(date_min),
        "max": str(date_max),
        "years_included": years,
    }


def main():
    args = parse_args()

    if not args.source:
        raise SystemExit(
            "Missing required argument: --source (no .hyper file to inspect was specified).\n"
            f"Usage:   {SOURCE_USAGE}\n"
            "Example: python3 scripts/generate_metadata.py --source=data/Finished_Merged.hyper"
        )
    hyper_file = args.source
    if not os.path.exists(hyper_file):
        raise SystemExit(f"{hyper_file} not found.")

    output_file = args.output or os.path.splitext(hyper_file)[0] + ".json"
    datasource_name = args.name or os.path.splitext(os.path.basename(hyper_file))[0].replace("_", " ")
    tags = sorted({t.strip() for t in args.tags.split(",") if t.strip()})

    # Calculated fields are author-supplied (this profiler can't invent
    # formulas), so if the output file already has a "calculations" block,
    # carry it forward rather than clobbering it when re-profiling.
    preserved_calculations = []
    if os.path.exists(output_file):
        try:
            with open(output_file) as f:
                preserved_calculations = json.load(f).get("calculations", [])
        except (json.JSONDecodeError, OSError):
            preserved_calculations = []

    with HyperProcess(Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU, "generatemetadata") as hyper:
        with Connection(hyper.endpoint, hyper_file) as connection:
            table_name, table_def = get_table_definition(connection, hyper_file)
            row_count = connection.execute_scalar_query(f"SELECT COUNT(*) FROM {table_name}")

            columns = []
            unprofiled_columns = []
            for col in table_def.columns:
                name = col.name.unescaped
                description = describe_column(connection, table_name, col, row_count)
                if description == NO_DESCRIPTION:
                    unprofiled_columns.append(name)
                columns.append(
                    {
                        "name": name,
                        "type": str(col.type),
                        "nullable": col.nullability == Nullability.NULLABLE,
                        "description": description,
                    }
                )

            date_stats = find_date_stats(connection, table_name, table_def)

    if unprofiled_columns:
        print(
            "Note: no description generated for these column(s) -- their type "
            f"isn't profiled by this script (e.g. bytes, json, geography): {unprofiled_columns}"
        )

    description = f"Hyper extract with {len(columns)} column(s) and {row_count} row(s)."
    if date_stats:
        description += (
            f" Spans {date_stats['min']} to {date_stats['max']}, based on the "
            f"{date_stats['column']!r} column."
        )

    metadata = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_file": hyper_file,
        "datasource": {
            "name": datasource_name,
            "description": description,
            "tags": tags,
            "certified": args.certified,
            "certification_note": args.certification_note,
        },
        "stats": {
            "row_count": row_count,
            **({
                "date_column": date_stats["column"],
                "date_min": date_stats["min"],
                "date_max": date_stats["max"],
                "years_included": date_stats["years_included"],
            } if date_stats else {}),
        },
        "columns": columns,
        **({"calculations": preserved_calculations} if preserved_calculations else {}),
        "column_description_disclaimer": COLUMN_DESCRIPTION_DISCLAIMER,
    }

    with open(output_file, "w") as f:
        json.dump(metadata, f, indent=2, default=str)

    print(f"Wrote metadata for {len(columns)} column(s) to {output_file}")
    if preserved_calculations:
        print(f"Preserved {len(preserved_calculations)} existing calculated field(s) from {output_file}.")
    summary = f"  {row_count} row(s)"
    if date_stats:
        summary += f", {date_stats['min']} to {date_stats['max']}, years: {date_stats['years_included']}"
    print(summary)


if __name__ == "__main__":
    main()
